################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/dk8moore/Desktop/embedded-project/External\ Libraries/adc.c \
/Users/dk8moore/Desktop/embedded-project/External\ Libraries/bmp280.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/bsp.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/debug.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_gpio.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_rtc.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_spi.c \
/Users/dk8moore/Desktop/embedded-project/External\ Libraries/i2c.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/main.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_hal_msp.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_hw.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_it.c \
/Users/dk8moore/Desktop/embedded-project/External\ Libraries/stm32l0xx_hal_i2c_ex.c \
/Users/dk8moore/Desktop/embedded-project/External\ Libraries/tsl2561.c \
/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/vcom.c 

OBJS += \
./Projects/End_Node/adc.o \
./Projects/End_Node/bmp280.o \
./Projects/End_Node/bsp.o \
./Projects/End_Node/debug.o \
./Projects/End_Node/hw_gpio.o \
./Projects/End_Node/hw_rtc.o \
./Projects/End_Node/hw_spi.o \
./Projects/End_Node/i2c.o \
./Projects/End_Node/main.o \
./Projects/End_Node/mlm32l0xx_hal_msp.o \
./Projects/End_Node/mlm32l0xx_hw.o \
./Projects/End_Node/mlm32l0xx_it.o \
./Projects/End_Node/stm32l0xx_hal_i2c_ex.o \
./Projects/End_Node/tsl2561.o \
./Projects/End_Node/vcom.o 

C_DEPS += \
./Projects/End_Node/adc.d \
./Projects/End_Node/bmp280.d \
./Projects/End_Node/bsp.d \
./Projects/End_Node/debug.d \
./Projects/End_Node/hw_gpio.d \
./Projects/End_Node/hw_rtc.d \
./Projects/End_Node/hw_spi.d \
./Projects/End_Node/i2c.d \
./Projects/End_Node/main.d \
./Projects/End_Node/mlm32l0xx_hal_msp.d \
./Projects/End_Node/mlm32l0xx_hw.d \
./Projects/End_Node/mlm32l0xx_it.d \
./Projects/End_Node/stm32l0xx_hal_i2c_ex.d \
./Projects/End_Node/tsl2561.d \
./Projects/End_Node/vcom.d 


# Each subdirectory must supply rules for building sources it contributes
Projects/End_Node/adc.o: /Users/dk8moore/Desktop/embedded-project/External\ Libraries/adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/bmp280.o: /Users/dk8moore/Desktop/embedded-project/External\ Libraries/bmp280.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/bsp.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/bsp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/debug.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/debug.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_gpio.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_rtc.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/hw_spi.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/hw_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/i2c.o: /Users/dk8moore/Desktop/embedded-project/External\ Libraries/i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/main.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_hal_msp.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_hw.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_hw.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/mlm32l0xx_it.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/mlm32l0xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/stm32l0xx_hal_i2c_ex.o: /Users/dk8moore/Desktop/embedded-project/External\ Libraries/stm32l0xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/tsl2561.o: /Users/dk8moore/Desktop/embedded-project/External\ Libraries/tsl2561.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Projects/End_Node/vcom.o: /Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/src/vcom.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/MLM32L07X01" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/CMSIS/Include" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Crypto" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Phy" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Utilities" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Core" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/Common" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/hts221" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps22hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/lps25hb" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/Components/sx1276" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/dk8moore/Desktop/embedded-project/STM32CubeExpansion_LRWAN_V1.1.4/Middlewares/Third_Party/Lora/Mac/region" -I"/Users/dk8moore/Desktop/Embedded Project/External Libraries" -I"/Users/dk8moore/Desktop/embedded-project/External Libraries"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


